In [ ]:
import numpy as np

# Create a NumPy array using a Python list
my_list = [10, 20, 30, 40, 50]
array = np.array(my_list)

# Display the array
print("NumPy Array:", array)

# Print the shape of the array
print("Shape of the array:", array.shape)

# Print the data type of the array
print("Data type of the array:", array.dtype)


NumPy Array: [10 20 30 40 50]
Shape of the array: (5,)
Data type of the array: int64


In [ ]:
import numpy as np

# Create a 3×4 matrix of zeros
zeros_matrix = np.zeros((3, 4))

# Create a 2×5 matrix of ones
ones_matrix = np.ones((2, 5))

# Print the matrices
print("3×4 Matrix of Zeros:")
print(zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2×5 Matrix of Ones:")
print(ones_matrix)
print("Shape:", ones_matrix.shape)


3×4 Matrix of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

2×5 Matrix of Ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [ ]:
import numpy as np

# Create a NumPy array with numbers from 1 to 12
original_array = np.arange(1, 13)

# Reshape the array into a 3×4 matrix
reshaped_array = original_array.reshape(3, 4)

# Display the arrays and their shapes
print("Original Array:")
print(original_array)
print("Shape:", original_array.shape)

print("\nReshaped 3×4 Matrix:")
print(reshaped_array)
print("Shape:", reshaped_array.shape)


Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped 3×4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [ ]:
import numpy as np

# Create a NumPy array of 10 random integers between 1 and 100
arr = np.random.randint(1, 101, 10)

# Display the array
print("Random Array:")
print(arr)

# Find minimum, maximum, mean, and sum
print("Minimum value:", arr.min())
print("Maximum value:", arr.max())
print("Mean value:", arr.mean())
print("Sum of values:", arr.sum())


Random Array:
[16 88 71 45 71 10 80 35 69 25]
Minimum value: 10
Maximum value: 88
Mean value: 51.0
Sum of values: 510


In [ ]:
import pandas as pd

# Create a dictionary with student names and marks
data = {
    'Student_Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Marks': [85, 90, 78, 88]
}

# Create a Pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print("Student DataFrame:")
print(df)

# Print data types of each column
print("\nData Types of Each Column:")
print(df.dtypes)



Student DataFrame:
  Student_Name  Marks
0        Alice     85
1          Bob     90
2      Charlie     78
3        David     88

Data Types of Each Column:
Student_Name    object
Marks            int64
dtype: object


In [ ]:
import pandas as pd

# Read the CSV file
# If wine.data has no header, specify header=None
df = pd.read_csv("wine.data", header=None)

# Display the first 5 records
print("First 5 records of the dataset:")
print(df.head())

# Display the last 5 records
print("\nLast 5 records of the dataset:")
print(df.tail())


First 5 records of the dataset:
   0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735  

Last 5 records of the dataset:
     0      1     2     3     4    5     6     7     8     9     10    11  \
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.7  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.3  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60   
177 

In [ ]:
import pandas as pd

# Load the dataset (replace with your file name or path)
df = pd.read_csv("wine.data", header=None)

# Display dataset structure
print("Dataset Information:")
df.info()

# Identify number of rows and columns
rows, columns = df.shape
print("\nNumber of Rows:", rows)
print("Number of Columns:", columns)

# Identify total number of missing values
missing_values = df.isnull().sum().sum()
print("Total Missing Values:", missing_values)


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       178 non-null    int64  
 1   1       178 non-null    float64
 2   2       178 non-null    float64
 3   3       178 non-null    float64
 4   4       178 non-null    float64
 5   5       178 non-null    int64  
 6   6       178 non-null    float64
 7   7       178 non-null    float64
 8   8       178 non-null    float64
 9   9       178 non-null    float64
 10  10      178 non-null    float64
 11  11      178 non-null    float64
 12  12      178 non-null    float64
 13  13      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

Number of Rows: 178
Number of Columns: 14
Total Missing Values: 0


In [ ]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("wine.data", header=None)

# Display statistical summary
print("Statistical Summary:")
print(df.describe())


Statistical Summary:
               0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.295112    2.029270    0.361854    1.590899    5.058090    0.957449   
std   